name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - libname: libwebp.so
            os: ubuntu-latest
          - libname: libwebp.dylib
            os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install tools
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install gcc make autoconf automake libtool
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install gcc make autoconf automake libtool
          fi
      - name: Build WebP lib
        working-directory: ./libwebp
        run: |
          ./autogen.sh
          ./configure --disable-static --disable-png --disable-jpeg --disable-tiff --disable-gif --disable-wic --disable-libwebpdecoder --disable-libwebpextras --disable-libwebpmux --disable-libwebpdemux --disable-sdl --prefix=$HOME/build
          make
          make install
      - name: Archive WebP lib
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.libname }}
          path: /home/runner/build/lib/${{ matrix.libname }}
