name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, macos-12]
        include:
          - suffix: so
            os: ubuntu-latest
            arch: x86_64
            install_tools_command: sudo apt-get update && sudo apt-get install gcc make autoconf automake libtool
          - suffix: dylib
            os: macos-14
            arch: aarch64
            install_tools_command: brew install gcc make autoconf automake libtool
          - suffix: dylib
            os: macos-12
            arch: x86_64
            install_tools_command: brew install gcc make autoconf automake libtool
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install tools
        run: ${{ matrix.install_tools_command }}
      - name: Build WebP lib
        working-directory: ./libwebp
        run: |
          ./autogen.sh
          ./configure \
          --disable-static \
          --disable-png \
          --disable-jpeg \
          --disable-tiff \
          --disable-gif \
          --disable-wic \
          --disable-libwebpdecoder \
          --disable-libwebpextras \
          --disable-libwebpmux \
          --disable-libwebpdemux \
          --disable-sdl \
          --prefix=${{ github.workspace }}/artifact
          make
          make install
      - name: Archive WebP lib
        uses: actions/upload-artifact@v2
        with:
          name: libwebp_${{ matrix.arch }}.${{ matrix.suffix }}
          path: ${{ github.workspace }}/artifact/lib/libwebp.${{ matrix.suffix }}
   
