name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Debug OS
        run: uname -a
      # - name: Init WebP git submodule
      #   working-directory: ./libwebp
      #   run: git submodule update --init --recursive
      - name: Debug
        working-directory: ./libwebp
        run: ls -la
      - name: Build WebP lib
        working-directory: ./libwebp
        run: ./configure --disable-static --disable-png --disable-jpeg --disable-tiff --disable-gif --disable-wic --disable-libwebpdecoder --disable-libwebpextras --disable-libwebpmux --disable-libwebpdemux --disable-sdl --prefix=$HOME/build
      - name: Run a one-line script
        run: echo Hello, world!
