name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, macos-12]
        include:
          - libname: libwebp_x86_64.so
            os: ubuntu-latest
          - libname: libwebp_x86_64.dylib
            os: macos-14
            arch: x86_64
          - libname: libwebp_aarch64.dylib
            os: macos-12
            arch: aarch64
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install tools
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install gcc make autoconf automake libtool
          elif [[ startsWith( "${{ matrix.os }}", "macos" ) ]]; then
            brew install gcc make autoconf automake libtool
          fi
      - name: Build WebP lib
        working-directory: ./libwebp
        run: |
          ./autogen.sh
          ./configure \
          --disable-static \
          --disable-png \
          --disable-jpeg \
          --disable-tiff \
          --disable-gif \
          --disable-wic \
          --disable-libwebpdecoder \
          --disable-libwebpextras \
          --disable-libwebpmux \
          --disable-libwebpdemux \
          --disable-sdl \
          --prefix=${{ github.workspace }}/artifact
          make
          make install
      - name: Archive WebP lib
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.libname }}
          path: ${{ github.workspace }}/artifact/lib/${{ matrix.libname }}
   
